//	VERSION 1.2
GL_PROC(PFNGLDRAWRANGEELEMENTSPROC, glDrawRangeElements);
GL_PROC(PFNGLTEXIMAGE3DPROC, glTexImage3D);
GL_PROC(PFNGLTEXSUBIMAGE3DPROC, glTexSubImage3D);
GL_PROC(PFNGLCOPYTEXSUBIMAGE3DPROC, glCopyTexSubImage3D);

//	VERSION 1.3
GL_PROC(PFNGLACTIVETEXTUREPROC, glActiveTexture);
GL_PROC(PFNGLSAMPLECOVERAGEPROC, glSampleCoverage);
GL_PROC(PFNGLCOMPRESSEDTEXIMAGE3DPROC, glCompressedTexImage3D);
GL_PROC(PFNGLCOMPRESSEDTEXIMAGE2DPROC, glCompressedTexImage2D);
GL_PROC(PFNGLCOMPRESSEDTEXIMAGE1DPROC, glCompressedTexImage1D);
GL_PROC(PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC, glCompressedTexSubImage3D);
GL_PROC(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC, glCompressedTexSubImage2D);
GL_PROC(PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC, glCompressedTexSubImage1D);
GL_PROC(PFNGLGETCOMPRESSEDTEXIMAGEPROC, glGetCompressedTexImage);

//	VERSION 1.4
GL_PROC(PFNGLBLENDFUNCSEPARATEPROC, glBlendFuncSeparate);
GL_PROC(PFNGLMULTIDRAWARRAYSPROC, glMultiDrawArrays);
GL_PROC(PFNGLMULTIDRAWELEMENTSPROC, glMultiDrawElements);
GL_PROC(PFNGLPOINTPARAMETERFPROC, glPointParameterf);
GL_PROC(PFNGLPOINTPARAMETERFVPROC, glPointParameterfv);
GL_PROC(PFNGLPOINTPARAMETERIPROC, glPointParameteri);
GL_PROC(PFNGLPOINTPARAMETERIVPROC, glPointParameteriv);
GL_PROC(PFNGLBLENDCOLORPROC, glBlendColor);
GL_PROC(PFNGLBLENDEQUATIONPROC, glBlendEquation);

//	VERSION 1.5
GL_PROC(PFNGLGENQUERIESPROC, glGenQueries);
GL_PROC(PFNGLDELETEQUERIESPROC, glDeleteQueries);
GL_PROC(PFNGLISQUERYPROC, glIsQuery);
GL_PROC(PFNGLBEGINQUERYPROC, glBeginQuery);
GL_PROC(PFNGLENDQUERYPROC, glEndQuery);
GL_PROC(PFNGLGETQUERYIVPROC, glGetQueryiv);
GL_PROC(PFNGLGETQUERYOBJECTIVPROC, glGetQueryObjectiv);
GL_PROC(PFNGLGETQUERYOBJECTUIVPROC, glGetQueryObjectuiv);
GL_PROC(PFNGLBINDBUFFERPROC, glBindBuffer);
GL_PROC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
GL_PROC(PFNGLGENBUFFERSPROC, glGenBuffers);
GL_PROC(PFNGLISBUFFERPROC, glIsBuffer);
GL_PROC(PFNGLBUFFERDATAPROC, glBufferData);
GL_PROC(PFNGLBUFFERSUBDATAPROC, glBufferSubData);
GL_PROC(PFNGLGETBUFFERSUBDATAPROC, glGetBufferSubData);
GL_PROC(PFNGLMAPBUFFERPROC, glMapBuffer);
GL_PROC(PFNGLUNMAPBUFFERPROC, glUnmapBuffer);
GL_PROC(PFNGLGETBUFFERPARAMETERIVPROC, glGetBufferParameteriv);
GL_PROC(PFNGLGETBUFFERPOINTERVPROC, glGetBufferPointerv);
