
uniform	sampler2D	texDiffuse;

struct V_INPUT{
	float3	vPosition : POSITION;
	float2	vTexCoord;
		
	uniform float4x4	mProj;
	uniform float4x4	mView;
	uniform float4x4	mModel;
};

struct V_OUTPUT{
	float4	vPosition : POSITION;
	float2	vTexCoord;
};

struct F_OUTPUT{
	float4	vColor : COLOR;
};

V_OUTPUT	vmain(V_INPUT vinput){
	V_OUTPUT	voutput;

	float4x4 mModelView = mul(vinput.mModel, vinput.mView);
	float4x4 mModelViewProj = mul(mModelView, vinput.mProj);
	float4	vPosition = mul(float4(vinput.vPosition, 1.0f), mModelViewProj);

	voutput.vPosition = vPosition;
	voutput.vTexCoord = vinput.vTexCoord;

	return voutput;
}

F_OUTPUT	fmain(V_OUTPUT finput){
	F_OUTPUT	foutput;

	foutput.vColor = tex2D(texDiffuse, finput.vTexCoord);

	return foutput;
}